### ISSUE TITLE
v0.14.0.5 - no MacOS version?

### ISSUE THREAD

**Issue by huglester** [LIMXTEC/BitSend#84]
Hello,

can you please also release MacOS build?

Thank you

**Comment by grantHarris** [comment]
I second this. A 0.14.0.5 release for MacOS would be helpful.

**Comment by grantHarris** [comment]
So I think there isn't a build for OSX because the OSX version fails on building the QT executable. (At least on my machine. I haven't tried to compile previous versions of BitSend before) Looking through the output it seems like an enum reference to BSD in BitsendUnits conflicts with a macro: 

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/param.h:72:13: note: 
      expanded from macro 'BSD'
#define BSD     199506          /* System version (year & month). */

I'm fooling around with this, but I may have a fix shortly. I managed to get it to compile by renaming the enum BSD to something else, but that's a bit of a hack and not suitable for a patch I feel.

**Comment by grantHarris** [comment]
See https://github.com/LIMXTEC/BitSend/pull/85

**Comment by limxdev** [comment]
Frank work on the MAC Wallet (OSX) Best Regards Christian

**Comment by dArkjON** [comment]
#85
